sisinfo-main/dinamico/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

sisinfo-main/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.list_posts, name='index'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.detail_post, name='detail'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
]

sisinfo-main/staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

sisinfo-main/posts/models.py
from django.db import models
from django.conf import settings


class Receita(models.Model):
    title = models.CharField(max_length=200)
    ingred = models.TextField(max_length=500, default='erro')
    mdf = models.TextField(max_length=1000, default = 'erro')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f'{self.title}'

sisinfo-main/staticpages/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    ingred = models.TextField(max_length=500, default='erro')
    mdf = models.TextField(max_length=1000, default = 'erro')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

sisinfo-main/posts/views.py
from django.http import HttpResponseRedirect
from .temp_data import post_data
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Receita


def list_posts(request):
    post_list = Receita.objects.all()
    context = {"post_list": post_list}
    return render(request, 'posts/index.html', context)

def detail_post(request, post_id):
    post = get_object_or_404(Receita, pk=post_id)
    context = {'post': post}
    return render(request, 'posts/detail.html', context)

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Receita.objects.filter(ingred__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)

def create_post(request):
    if request.method == 'POST':
        post_title = request.POST['title']
        post_ingred = request.POST['ingred']
        post_mdf = request.POST['mdf']
        post = Receita(title=post_title,
                      ingred=post_ingred,
                      mdf=post_mdf)
        post.save()
        return HttpResponseRedirect(
            reverse('posts:detail', args=(post.id, )))
    else:
        return render(request, 'posts/create.html', {})
    
def update_post(request, post_id):
    post = get_object_or_404(Receita, pk=post_id)

    if request.method == "POST":
        post.title = request.POST['title']
        post.ingred = request.POST['ingred']
        post.mdf = request.POST['mdf']
        post.save()
        return HttpResponseRedirect(reverse("posts:detail", args=(post.id, )))
    context = {'post': post}
    return render(request, 'posts/update.html', context)

def delete_post(request, post_id):
    post = get_object_or_404(Receita, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('posts:index'))
    context = {'post': post}
    return render(request, 'posts/delete.html', context)

sisinfo-main/staticpages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

sisinfo-main/posts/templates/posts/create.html
{% extends 'base.html' %} {% block content %}
<h2>Inserir Nova Receita</h2>
<form method="POST" action="{% url 'posts:create' %}">
  {% csrf_token %}
  <p>
    <label for="id_title">Receita:</label>
    <input type="text" name="title" id="id_title" />
  </p>
  <p>
    <label for="id_ingred">Ingredientes</label>
    <input type ="text" name="ingred" id="id_ingred" />
  </p>
  <p>
    <label for="id_mdf">Modo de fazer:</label>
    <input type ="text" name="mdf" id="id_mdf" />
  </p>
  <button type="submit">Criar</button>
</form>

{% if post.created_at %}
<p>Postado em: {{ post.created_at|date:"d/m/Y H:i" }}</p>
{% endif %}

{% endblock content %}

sisinfo-main/posts/templates/posts/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="POST">
  {% csrf_token %}
  <p>Você tem certeza que deseja apagar o filme "{{ post.title }} "?</p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

sisinfo-main/posts/templates/posts/detail.html
{% extends 'base.html' %} {% block title %} {{ post.title }} ({{
    post.content }} {% endblock title %} {% block content %}
    <h2>Detalhes da receita {{ post.title }}</h2>
    
    <section class="dados-da-receita">
        <h3>Ingredientes:</h3> {{ post.ingred }}
        <h3>Modo de fazer:</h3> {{ post.mdf }}
        <p>Publicado em: {{ post.created_at|date:"d M Y H:i" }}</p>
        <p>Atualizado em: {{ post.updated_at|date:"d M Y H:i" }}</p>
        <a href="{% url 'posts:update' post.id %}">Editar</a> </br></br>
        <a href="{% url 'posts:delete' post.id %}">Excluir</a>
    </section>
    
    {% endblock content %}

sisinfo-main/posts/templates/posts/index.html
{% extends 'base.html' %} {% block content %}
<h2>Todos as Receitas</h2>
<section>
  <p>
    Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Receitas</a>
  </p>
  <p>
    Não encontrou a receita?
    <a href="{% url 'posts:create' %}">Adicionar Nova Receita</a>
  </p>
</section>
{% if post_list %}
<section class="lista-de-cards">
  {% for post in post_list %}
  <article class="card">
    <p>{{ post.title }}</p>
    <a href="{% url 'posts:detail' post.id %}"
      >Detalhes</a>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma receita.</p>
{% endif %} {% endblock content %}

sisinfo-main/posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Receitas por Ingredientes</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Ingrediente:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <p>{{ post.title }}</p>
        <a href="{% url 'posts:detail' forloop.counter %}">Detalhes</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma receita com esse ingrediente.</p>
{% endif %}

{% endblock content %}

sisinfo-main/posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<h2>Atualizar Dados da Receita {{ post.title }} </h2>
<form method="POST" action="{% url 'posts:update' post.id %}">
    {% csrf_token %}
    <p>
        <label for="id_title">Receita:</label>
        <input type="text" name="title" id="id_title" value="{{ post.title }}" />
    </p>
    <p>
        <label for=" id_ingred">Ingredientes:</label>
        <input type="text" name="ingred" id="id_ingred" value="{{ post.ingred }}" />
    </p>
    <p>
        <label for=" id_mdf">Modo de fazer:</label>
        <input type="text" name="mdf" id="id_mdf" value="{{ post.mdf }}" />
    </p>
    <button type="submit">Atualizar </button>
    </form>
{% endblock content %}

sisinfo-main/staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
Criado para ajudar pessoas inciantes na cozinha a fazer o que é basico, porém essencial.  <br />
Rápido, simples e prático. 
{% endblock content %}

sisinfo-main/staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>De barriga cheia!</i></h1>
<p>Tutoriais simples para aqueles que não sabem nem cozinhar arroz... (eu também era assim)</p> <br/>



<section id="post">
    {% for post in post_list %}
    <article>
        <header id="cabecalho-post">
            <p>Publicado em: {{ post.created_at|date:"d M Y H:i" }}</p>
            <p>Atualizado em: {{ post.updated_at|date:"d M Y H:i" }}</p>
        </header>
        <main id="conteiner-principal">
            <h4>{{ post.title }}</h4>
            <div>{{ post.ingred|safe }}</div>
            <div>{{ post.mdf|safe }}</div>
        </main>
    </article>
    {% endfor %}
</section>
{% endblock content %}

sisinfo-main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | De barriga cheia!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> 
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.jpeg' %}"  style="width:150px;"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Receitas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2024</small>
        </p>
    </footer>
</body>

</html>